import AntheaBlouse from './img/AntheaBlouse.webp';
import PomonaShorts from './img/PomonaShorts.webp';
import PersephonePants from './img/PersephoneTrousers.webp';
import LaurenceTop from './img/LaurenceTop.webp';
import OrchadDress from './img/OrchadDress.webp';
import BisqueTrousers from './img/BisqueTrousers.webp';
import WestEndJacket from './img/WestEndJacket.webp';
import PeplumTop from './img/PeplumTop.webp';
import PeppermintWrapTop from './img/PeppermintWrapTop.webp';
import RuffledSleeveTop from './img/RuffledSleeveTop.webp';
import FlorDressAndTop from './img/FlorDressAndTop.webp';
import SerpentineHat from './img/SerpentineHat.webp';
import HinterlandDress from './img/HinterlandDress.webp';

export const garments = [
  {
    name: 'Anthea blouse and dress',
    link: 'https://annaallenclothing.com/collections/all-products/products/anthea-blouse-dress-pdf-sewing-pattern-sizes-00-22',
    author: 'Anna Allen Clothing',
    image: AntheaBlouse,
    description:
      'Blouse or dress with puffed sleeves, button up the front with a fold-over placket and bias faced neckline. Puffed sleeves end at, or below the elbow with a narrow bias cuff. Hemline dips down at the back/front and comes up slightly at the side seams. The dress includes a separate tie.',
    category: 'tops',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Pomona pants and shorts',
    link: 'https://annaallenclothing.com/collections/all-products/products/pomona-pants-shorts',
    author: 'Anna Allen Clothing',
    image: PomonaShorts,
    description: `High rise and loose fitting pants with elastic waist. They are without side seams and include patch pockets on the front or back. The waistband is created by folding over the top edge of the pant. Legs can be wide, ankle length or loose tapered also ankle length.`,
    category: 'bottoms',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Persephone pants',
    link: 'https://annaallenclothing.com/collections/all-products/products/persephone-pants-shorts',
    author: 'Anna Allen Clothing',
    image: PersephonePants,
    description: `High waist pants and shorts in US navy sailor style from 20'-40'. Pants are without side seams. The front and back pant legs are cut from one piece. It has a button fly, in-seam pockets, belt loops, and two back waist darts.`,
    category: 'bottoms',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Laurence top',
    link: 'https://www.vivianshaochen.com/patterns/laurence-top',
    author: '',
    image: LaurenceTop,
    description: `This top sewing pattern featuring two options. A v-neck sleeveless top or a scoop-neck three-quarter sleeve top, or combination of it. Pattern comes in cropped length above th hips.`,
    category: 'tops',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Orchad dress',
    link: '',
    author: '',
    image: OrchadDress,
    description: 'bgbddbalba',
    category: 'dress',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Bisque trousers',
    link: '',
    author: '',
    image: BisqueTrousers,
    description: 'bdffbnbasbsbbalba',
    category: 'bottoms',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'The west end jacket',
    link: '',
    author: '',
    image: WestEndJacket,
    description: 'wrgabfdbnetjyjshhf',
    category: 'tops',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Peplum top',
    link: '',
    author: '',
    image: PeplumTop,
    description: 'sgrababza',
    category: 'tops',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Peppermint wrap top',
    link: '',
    author: '',
    image: PeppermintWrapTop,
    description: 'bfdhabahjnz',
    category: 'tops',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Ruffled sleeved top',
    link: '',
    author: '',
    image: RuffledSleeveTop,
    description: 'brhetrsdtyabahjnz',
    category: 'tops',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Flor dress and top',
    link: '',
    author: '',
    image: FlorDressAndTop,
    description: 'bfdhabndnddgdahjndz',
    category: 'tops',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Serpentine hat',
    link: '',
    author: '',
    image: SerpentineHat,
    description: 'iyutrhgefbfdhabahjnz',
    category: 'accessories ',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
  {
    name: 'Hinterland dress',
    link: '',
    author: '',
    image: HinterlandDress,
    description: 'bfdhabahjnz',
    category: 'dress',
    measurements: '',
    fabric: '',
    notes: '',
    state: '',
  },
];
